### ISSUE TITLE
Running local API alongside prerendercloud-server

### ISSUE THREAD

**Issue by brandondurham** [sanfrancesco/prerendercloud-server#1]
Hiya. I have a client-side app that I’m trying to render out. Most everything seems to be working, but I’m having one issue that I’m sure I’m just missing in the docs.

My app (let’s call it my-app.com) runs a small Express app that creates a local proxy to my remote API. So when I start my app up I run `node server` to start the proxy, then I’m able to send my API requests through `https://my-app.com/api/v1` which sends that request to `https://api.my-app.com/v1/`.

I’m unclear as to how I should get `node server` running along with `prerendercloud-server build` so my API works. Might you have any suggestions?

**Comment by jotto** [comment]
Sorry for the 3 year delay. This response is for posterity.

This project will now achieve what you've described if a file with the name `_redirects` exists in the wwwroot. That file, in your case, would look like:

```
/api/v1/* https://api.my-app.com/v1/:splat 200
```

Read more here: https://github.com/sanfrancesco/prerendercloud-server#the-_redirects-file
